name: mountain-tapir
version: "1.1.0"
summary: Mountain Tapir Collage Maker is a tool for combining images into collages.
description: Mountain Tapir allows users to arrange images into a collage, and save the result as a new image.
confinement: strict
icon: "docs/icon.png"
grade: stable
epoch: 0

apps:
  mountain-tapir:
    command: desktop-launch $SNAP/mountain_tapir.sh
    plugs: [unity7, x11, gsettings, home]
    desktop: mountain-tapir.desktop
  tclsh:
    # Wrap tclsh so that it works in the virtual environment (see http://stackoverflow.com/a/39217712/171296).
    command: tclsh.wrapper
    plugs: [home, unity7, network, x11]

parts:
  mountain-tapir:
    plugin: python
    python-version: python3
    source: .
    stage-packages:
     - python
     - python3-tk
    python-packages:
     - image
    after: [desktop-gtk2]
  mountain-tapir-copy:
    plugin: dump
    source: mountain_tapir
  wrappers:
    plugin: dump
    source: wrappers
